# Use the official Node.js image
FROM node:20-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install all dependencies, including dev dependencies
RUN npm install --legacy-peer-deps

# Copy the entire application source code
COPY . .

# Install development dependencies
RUN npm install --only=development --legacy-peer-deps

# Generate Prisma client for the current schema
RUN npx prisma generate

# Expose the application port and debug port
EXPOSE 3000
EXPOSE 9229

# Use nodemon for hot-reloading during development
CMD ["npm", "run", "start:dev"]
