services:
  postgres:
    image: postgres:14
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: community_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
   # image: kunjan16/community-backend:dev
    container_name: nestjs-app-dev
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: community_dev
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app   # Maps your host directory to the container
      - /usr/src/app/node_modules   # Avoid conflicts with node_modules
    command: npm run start:dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

volumes:
  postgres_data_dev:
